### ISSUE TITLE
e-mail us - Button looks like a search field

### ISSUE THREAD

**Issue by 7coil** [rhul-compsoc/computingsociety.co.uk#14]
![image](https://user-images.githubusercontent.com/13886925/137291051-adced531-c5ee-442b-9e86-6fa440dfb226.png)

If Carlos Matos says so, it must be true!
Sorry @jcsawyer123

**Comment by jcsawyer123** [comment]
https://material.io/components/buttons#anatomy


To fix either lower the thickness of the border and embolden the text.  

Or

Make it a solid button. However, outlined buttons are set a visual hierarchy whereby the outlined button is less important than the filled. 


If you make all buttons on the site bold that will also help
